// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ftmrpatjcvqreyirnphg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ0bXJwYXRqY3ZxcmV5aXJucGhnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODE5NDk2ODAsImV4cCI6MjA5NzUyNTY4MH0.kXcJ9oqVliAAztUJGrtyWtS9pma7xBZNTl_gXx3zEPc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});